### ISSUE TITLE
Where are the files?

### ISSUE THREAD

**Issue by vsoch** [fomightez/yeast_snornas#1]
I'm wanting to learn about analysis of yeast, but I don't see any files in the repository here, other than the README.md. Am I looking in the wrong place? Thank you!

**Comment by fomightez** [comment]
Hi. Sorry, this is related to an ongoing project to update and move the former [UMass yeast snoRNA database](https://people.biochem.umass.edu/fournierlab/snornadb/mastertable.php). I plan to update this when I do that. In the interim if you have a list of genes to analyze please contact me via my Upstate Medical University email.

**Comment by vsoch** [comment]
Oh, no worries! I'm actually less of a code curious biologist, most of a biology curious coder - I'm looking to learn about analyzing yeast data, and the best way for me is via trying things out. No worries about needing genes analyzed, but if you do have some good learning resources (coding with data) I'd love to share! Thanks and closing issue.

**Comment by fomightez** [comment]
The examples in [my BLAST binder](https://github.com/fomightez/blast-binder) are mostly yeast; however, not RNA. Go [there](https://github.com/fomightez/blast-binder) and press `launch binder`.

My yeastmine related items may also interest you:

https://github.com/fomightez/yeastmine

https://github.com/fomightez/guide_to_intermine-binder

https://github.com/fomightez/intermine-binder

**Comment by vsoch** [comment]
I forgot to say thank you! I'll be digging in to these very soon :)
